service: dynamodb-athena-analytics

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 300
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: "*"

package:
  exclude:
    - node_modules/aws-sdk/**
    - node_modules/lodash/**

functions:
  produce:
    handler: dynamo-producer.insert
    events:
      - schedule: rate(5 minutes)
  consume-from-dynamo:
    handler: dynamo-stream-handler.write_to_kinesis
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - DynamoDbTable
              - StreamArn
          batchSize: 10

resources:  
  Resources:
    S3BucketAthena:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: james-athena-analytics-bucket
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dynamo-table-name
        AttributeDefinitions:
          - AttributeName: event_uuid
            AttributeType: S
        KeySchema:
          - AttributeName: event_uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 10
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    MessageDeliveryStream:
        Type: "AWS::KinesisFirehose::DeliveryStream"
        Properties: 
          DeliveryStreamName: dynamo-s3-delivery-stream
          S3DestinationConfiguration:
            BucketARN: 
              Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: S3BucketAthena
            BufferingHints: 
              IntervalInSeconds: "60"
              SizeInMBs: "50"
            CompressionFormat: "UNCOMPRESSED"
